# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c98a410c3f26a4b1d6f7ba9b6a29b12af4450695349237b789778b0cbecd8e27f825687e245ce7949ed9cff0dd4990f6390ecb673d80abc72c62ea8ce1f3d10f

test:
  secret_key_base: c0754b639090a851925519e941ef6b858511bf08e3209f9843d50c1409e28585bf8de810bf8824df5a4984fdda9ee101c4f1eb21ef484845c5e425cbe84779ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
